language: elixir
sudo: false
elixir: 1.5.2
otp_release: 20.1

env:
  - MIX_ENV=test

before_script:
  - mix deps.compile

script:
  - mix compile --warnings-as-errors
  - mix credo
  - mix coveralls.travis
